### ISSUE TITLE
License

### ISSUE THREAD

**Issue by zauni** [newagebegins/pacman#1]
Hello @newagebegins 
which license has your pacman implementation? Because without a license your code is almost like closed source and nobody can legally use it or modify it. Maybe this can help: http://choosealicense.com/

Thanks for your time and this nice pacman game!

**Comment by newagebegins** [comment]
Hello @zauni
I'm glad that you liked the game! Added LICENSE.txt for MIT license.

**Comment by zauni** [comment]
Thank you very much!
